@AspLongTaskCancellation_HostAddress = http://localhost:5230

GET {{AspLongTaskCancellation_HostAddress}}/LongRunning/WithoutCancellationToken
Accept: application/json

###
GET {{AspLongTaskCancellation_HostAddress}}/LongRunning/WithCancellationToken
Accept: application/json