name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' 

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build --configuration Release --no-restore src

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal src
